"""SDUI (Server-Driven UI) Pydantic schemas for plugin dashboard pages.

Exports all 39 primitive models plus the ``node()`` helper and supporting
sub-models.  Import from here rather than from ``primitives`` directly::

    from codehome.serve.sdui import Stack, Button, Alert, node
"""

from codehome.serve.sdui.cli_runner import run_command
from codehome.serve.sdui.commands import CommandError, CommandProgress, CommandResult
from codehome.serve.sdui.primitives import (
    Alert,
    Badge,
    Breadcrumb,
    BreadcrumbItem,
    Button,
    Card,
    Checkbox,
    Code,
    ColumnDef,
    Confirm,
    DataGrid,
    DataGridColumnDef,
    Diff,
    Divider,
    Drawer,
    Empty,
    Grid,
    Heading,
    Input,
    JsonView,
    KeyValue,
    KVEntry,
    List,
    Logs,
    Markdown,
    Modal,
    OptionItem,
    Popover,
    ProgressBar,
    Radio,
    SDUINode,
    Select,
    Slider,
    Spacer,
    Spinner,
    Stack,
    Status,
    Switch,
    TabItem,
    Table,
    Tabs,
    Text,
    TextArea,
    Timeline,
    TimelineItem,
    Toast,
    Tree,
    ZStack,
    node,
)

__all__ = [
    "Alert",
    "Badge",
    "Breadcrumb",
    "BreadcrumbItem",
    "Button",
    "Card",
    "Checkbox",
    "Code",
    "ColumnDef",
    "CommandError",
    "CommandProgress",
    "CommandResult",
    "Confirm",
    "DataGrid",
    "DataGridColumnDef",
    "Diff",
    "Divider",
    "Drawer",
    "Empty",
    "Grid",
    "Heading",
    "Input",
    "JsonView",
    "KVEntry",
    "KeyValue",
    "List",
    "Logs",
    "Markdown",
    "Modal",
    "OptionItem",
    "Popover",
    "ProgressBar",
    "Radio",
    "SDUINode",
    "Select",
    "Slider",
    "Spacer",
    "Spinner",
    "Stack",
    "Status",
    "Switch",
    "TabItem",
    "Table",
    "Tabs",
    "Text",
    "TextArea",
    "Timeline",
    "TimelineItem",
    "Toast",
    "Tree",
    "ZStack",
    "node",
    "run_command",
]
