"""Plugin loader: import enabled plugins and register into the plugin registry.

Bridge between discovery/state and the registry.  Discovers plugins on
disk, reconciles with persisted state, topologically sorts by declared
dependencies, then imports each enabled plugin's handler modules
(``handlers.py``, ``routes.py``, ``checks.py``) and extracts the
callables that the registry needs.

Event subscriptions (``@on()`` decorators) are loaded lazily from
``events.toml`` (generated by ``v plugins rescan``).  The handler
module is only imported on the first event fire, avoiding eager imports
at startup.

A broken or missing plugin never crashes the CLI -- errors are
accumulated and returned alongside the count of successfully loaded
plugins.
"""

from __future__ import annotations

import asyncio
import importlib.util
import logging
import sys
from typing import TYPE_CHECKING, Any

from supervisor.dynamic_import import import_module_from_path

from supervisor.checks.registry import _registry as check_registry
from supervisor.plugins import registry
from supervisor.plugins.discovery import check_system_deps, discover_plugins
from supervisor.plugins.state import load_state, merge_discovered, save_state
from supervisor.plugins.subscription_parser import Subscription, read_events_toml

if TYPE_CHECKING:
    from collections.abc import Callable, Coroutine
    from pathlib import Path
    from types import ModuleType

    from supervisor.bus.types import Event
    from supervisor.plugins.manifest import PluginManifest

log = logging.getLogger(__name__)

# Tracks which (plugin, event, handler) triples have been subscribed to the
# bus so that the second load_all_plugins() call (server startup) does not
# duplicate subscriptions.  Mirrors the check_registry dedup guard.
_installed_subscriptions: set[tuple[str, str, str]] = set()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def load_all_plugins(root: Path) -> tuple[int, list[str]]:
    """Discover, reconcile, sort, and load all enabled plugins.

    Called twice during normal operation:

    1. **CLI startup** (``cli.py`` / ``build_parser``): Loads plugins so
       their CLI commands appear in the argparse tree.
    2. **Server startup** (``serve/server.py`` / lifespan): Loads again
       so plugin checks are registered into CheckRegistry and routers
       are available for mounting.

    Idempotency is maintained by two mechanisms:
    - ``registry.clear()`` wipes the plugin registry before each load,
      so stale entries from a previous call are removed.
    - Check registration skips names already present in CheckRegistry
      (see the ``if decl.name in check_registry: continue`` guard below),
      since checks registered during call #1 persist in the module-level
      singleton and should not be duplicated.

    Args:
        root: Absolute path to the super/ project root.

    Returns:
        A ``(loaded_count, errors)`` tuple where *loaded_count* is the
        number of plugins successfully registered and *errors* collects
        human-readable messages for anything that went wrong.

    """
    errors: list[str] = []

    # 1. Discover plugins on disk.
    discovered = discover_plugins(root)
    errors.extend(discovered.errors)

    # 2. Reconcile with persisted state.
    old_state = load_state(root)
    new_state = merge_discovered(old_state, discovered.plugins)
    save_state(root, new_state)

    # 3. Topological sort so dependencies load first.
    try:
        ordered = _topological_sort(discovered.plugins)
    except RuntimeError as exc:
        errors.append(str(exc))
        return 0, errors

    # 4. Clear the registry before a full reload.
    registry.clear()
    _installed_subscriptions.clear()

    loaded = 0
    for plugin_dir, manifest in ordered:
        name = manifest.name

        # Only load plugins whose merged state says "enabled".
        if not new_state["plugins"].get(name, {}).get("enabled", False):
            continue

        # Check system-level dependencies (e.g. `ssh`, `mkcert`).
        missing = check_system_deps(manifest)
        if missing:
            errors.append(f"plugin '{name}': missing system deps: {', '.join(missing)}")
            continue

        # Pre-load this plugin's _sdk.py into sys.modules so that
        # ``from _sdk import ...`` works across all plugin files
        # (handlers.py, routes.py, checks.py). Cleaned up after all
        # files for this plugin are loaded.
        sdk_path = plugin_dir / "_sdk.py"
        _sdk_loaded = False
        if sdk_path.exists():
            sdk_spec = importlib.util.spec_from_file_location(f"_plugin_{name}__sdk", sdk_path)
            if sdk_spec and sdk_spec.loader:
                sdk_mod = importlib.util.module_from_spec(sdk_spec)
                sys.modules["_sdk"] = sdk_mod
                sdk_spec.loader.exec_module(sdk_mod)
                _sdk_loaded = True

        # -- Import optional modules and extract callables ----------------
        cli_registrar = None
        router = None

        # handlers.py -- CLI registration function.
        if manifest.commands:
            handlers_path = plugin_dir / "handlers.py"
            if handlers_path.is_file():
                mod = _import_module_from_file(name, handlers_path)
                if mod is not None:
                    cli_registrar = getattr(mod, "register_cli", None)
                    if cli_registrar is None:
                        errors.append(f"plugin '{name}': handlers.py has no 'register_cli' function")
                    elif not callable(cli_registrar):
                        errors.append(f"plugin '{name}': 'register_cli' in handlers.py is not callable")
                        cli_registrar = None
                else:
                    errors.append(f"plugin '{name}': failed to import handlers.py")
            else:
                errors.append(f"plugin '{name}': declares commands but handlers.py not found")

        # routes.py -- FastAPI APIRouter for dashboard integration.
        if manifest.dashboard is not None:
            routes_path = plugin_dir / "routes.py"
            if routes_path.is_file():
                mod = _import_module_from_file(name, routes_path)
                if mod is not None:
                    router = getattr(mod, "router", None)
                    if router is None:
                        errors.append(f"plugin '{name}': routes.py has no 'router' attribute")
                else:
                    errors.append(f"plugin '{name}': failed to import routes.py")
            else:
                errors.append(f"plugin '{name}': declares dashboard but routes.py not found")

        # checks.py -- register check functions directly into CheckRegistry,
        # matching the extensions pattern (no intermediate check_fns dict).
        if manifest.checks:
            checks_path = plugin_dir / "checks.py"
            if checks_path.is_file():
                mod = _import_module_from_file(name, checks_path)
                if mod is not None:
                    for decl in manifest.checks:
                        fn = getattr(mod, decl.handler, None)
                        if fn is None:
                            errors.append(
                                f"plugin '{name}': checks.py has no function '{decl.handler}' for check '{decl.name}'"
                            )
                        elif not callable(fn):
                            errors.append(
                                f"plugin '{name}': '{decl.handler}' in checks.py is not callable (check '{decl.name}')"
                            )
                        else:
                            # Skip if already registered (e.g. from a
                            # previous load_all_plugins call).
                            if decl.name in check_registry:
                                continue
                            check_registry.register(
                                name=decl.name,
                                group=decl.group,
                                timeout=decl.timeout,
                                cwd=decl.cwd,
                                depends_on=decl.depends_on,
                                advisory=decl.advisory,
                                fn=fn,
                                source=f"plugin:{name}",
                            )
                else:
                    errors.append(f"plugin '{name}': failed to import checks.py")
            else:
                errors.append(f"plugin '{name}': declares checks but checks.py not found")

        # Remove the generic "_sdk" alias but keep the unique name so that
        # deferred calls (e.g., register_cli at argparse build time) can
        # still resolve imports from _sdk via the cached module.
        if _sdk_loaded:
            sys.modules.pop("_sdk", None)

        # -- Register the assembled plugin --------------------------------
        loaded_plugin = registry.LoadedPlugin(
            name=name,
            version=manifest.version,
            description=manifest.description,
            plugin_dir=str(plugin_dir),
            manifest=manifest,
            cli_registrar=cli_registrar,
            router=router,
        )
        registry.register(loaded_plugin)

        # -- Lazy event subscriptions from events.toml ---------------------
        _install_lazy_subscriptions(name, plugin_dir, errors)

        loaded += 1

    # 5. Validate cross-plugin state reads against loaded plugins.
    _validate_cross_plugin_reads(registry._plugins, errors)

    return loaded, errors


# ---------------------------------------------------------------------------
# Cross-plugin state read validation
# ---------------------------------------------------------------------------


def _validate_cross_plugin_reads(
    loaded_plugins: dict[str, registry.LoadedPlugin],
    errors: list[str],
) -> None:
    """Validate that ``reads_state`` entries reference existing plugins.

    Each entry follows the format ``plugin:scope:name`` or ``plugin:scope``.
    The first segment identifies the target plugin -- this function checks
    that the target is actually loaded.  Unknown targets are logged as
    errors AND added to the errors list.

    Note: this runs after all plugins have loaded, so load order does not
    affect validation.  A failure here means the target plugin is missing
    or disabled, not just loaded later.  We keep the error non-fatal
    (don't abort the CLI) because the dependent plugin may still function
    without the cross-read, but the prominent log.error ensures operators
    notice the broken declaration.
    """
    known = set(loaded_plugins.keys())
    for name, plugin in loaded_plugins.items():
        for read_decl in plugin.manifest.reads_state:
            parts = read_decl.split(":")
            if not parts:
                continue
            target_plugin = parts[0]
            if target_plugin not in known:
                msg = f"plugin {name!r}: reads_state={read_decl!r} references unknown plugin {target_plugin!r}"
                log.error(msg)
                errors.append(msg)


# ---------------------------------------------------------------------------
# Lazy event subscriptions
# ---------------------------------------------------------------------------


def _install_lazy_subscriptions(
    plugin_name: str,
    plugin_dir: Path,
    errors: list[str],
) -> None:
    """Read events.toml and register lazy bus subscriptions.

    Each subscription gets a wrapper that defers the actual module import
    until the first time the event fires.  This avoids importing plugin
    modules at startup just for event wiring.

    Idempotent: a (plugin, event, handler) triple is only subscribed once
    across multiple ``load_all_plugins()`` calls.
    """
    from supervisor.bus.instance import bus

    subs = read_events_toml(plugin_dir)
    if not subs:
        return

    for sub in subs:
        key = (plugin_name, sub.event_name, sub.handler_name)
        if key in _installed_subscriptions:
            continue

        handler = _make_lazy_handler(plugin_name, plugin_dir, sub)
        bus.subscribe(sub.event_name, handler)
        _installed_subscriptions.add(key)
        log.debug(
            "plugin '%s': lazy subscription %s -> %s.%s",
            plugin_name,
            sub.event_name,
            sub.module,
            sub.handler_name,
        )


def _make_lazy_handler(
    plugin_name: str,
    plugin_dir: Path,
    sub: Subscription,
) -> Callable[[Event], Coroutine[Any, Any, Any]]:
    """Create a handler that lazy-imports the module on first call.

    Uses the existing ``_import_module_from_file`` helper for consistency
    with how handlers.py / routes.py / checks.py are loaded.  The
    imported function reference is cached after the first invocation so
    subsequent calls go straight to the real handler.
    """
    _cache: dict[str, Callable[..., Any] | None] = {}
    # Sentinel: stored under "fn" when import or lookup fails so we
    # don't re-attempt (and re-log) on every subsequent event fire.
    _FAILED: Callable[..., Any] | None = None

    async def _lazy(event: Event) -> Any:
        if "fn" not in _cache:
            module_path = plugin_dir / f"{sub.module}.py"
            mod = _import_module_from_file(plugin_name, module_path)
            if mod is None:
                log.error(
                    "plugin '%s': failed to lazy-import %s for event '%s'",
                    plugin_name,
                    module_path,
                    sub.event_name,
                )
                _cache["fn"] = _FAILED
                return None
            fn = getattr(mod, sub.handler_name, None)
            if fn is None:
                log.error(
                    "plugin '%s': %s.py has no function '%s'",
                    plugin_name,
                    sub.module,
                    sub.handler_name,
                )
                _cache["fn"] = _FAILED
                return None
            _cache["fn"] = fn

        fn = _cache["fn"]
        if fn is _FAILED:
            return None
        assert fn is not None
        if asyncio.iscoroutinefunction(fn):
            return await fn(event)
        return fn(event)

    # Give the wrapper a meaningful name for logging/debugging.
    _lazy.__name__ = f"lazy:{plugin_name}.{sub.module}.{sub.handler_name}"
    _lazy.__qualname__ = _lazy.__name__
    return _lazy


# ---------------------------------------------------------------------------
# Topological sort
# ---------------------------------------------------------------------------


def _topological_sort(
    plugins: list[tuple[Path, PluginManifest]],
) -> list[tuple[Path, PluginManifest]]:
    """Sort *plugins* so that dependencies appear before dependents.

    Plugins whose declared dependencies are not present in the
    discovered set are skipped with a log warning (they cannot be
    satisfied).  Circular dependencies raise :class:`RuntimeError`.

    Uses iterative DFS with three-colour marking:
    - white (unvisited)
    - grey  (in current DFS path -- cycle if revisited)
    - black (fully processed)
    """
    by_name: dict[str, tuple[Path, PluginManifest]] = {m.name: (p, m) for p, m in plugins}

    WHITE, GREY, BLACK = 0, 1, 2
    colour: dict[str, int] = dict.fromkeys(by_name, WHITE)
    order: list[str] = []

    # Filter out plugins with unmet (undiscovered) dependencies.
    available: set[str] = set(by_name)
    skipped: set[str] = set()
    for name, (_dir, manifest) in by_name.items():
        for dep in manifest.dependencies:
            if dep not in available:
                log.warning(
                    "plugin '%s' skipped: dependency '%s' not found",
                    name,
                    dep,
                )
                skipped.add(name)
                break

    def _visit(name: str) -> None:
        """Push nodes to *order* in dependency-first order via iterative DFS."""
        # Stack entries: (node, iterator_over_deps).
        stack: list[tuple[str, list[str]]] = [(name, list(by_name[name][1].dependencies))]
        colour[name] = GREY

        while stack:
            current, deps = stack[-1]

            if deps:
                dep = deps.pop()
                if dep in skipped:
                    # Transitively skip: current depends on a skipped plugin.
                    skipped.add(current)
                    # Unwind the stack -- mark everything as black to avoid
                    # re-processing, but don't add to order.
                    for node, _ in stack:
                        colour[node] = BLACK
                    log.warning(
                        "plugin '%s' skipped: dependency '%s' was skipped",
                        current,
                        dep,
                    )
                    return
                if colour[dep] == GREY:
                    # Extract the full cycle path from the DFS stack.
                    cycle_nodes = [n for n, _ in stack]
                    # Find where 'dep' first appears -- that's the cycle start.
                    try:
                        start_idx = cycle_nodes.index(dep)
                    except ValueError:
                        start_idx = 0
                    cycle_path = [*cycle_nodes[start_idx:], dep]
                    msg = f"circular dependency detected among plugins: {' -> '.join(repr(n) for n in cycle_path)}"
                    raise RuntimeError(msg)
                if colour[dep] == WHITE:
                    colour[dep] = GREY
                    stack.append((dep, list(by_name[dep][1].dependencies)))
            else:
                # All deps processed; finalise this node.
                stack.pop()
                colour[current] = BLACK
                order.append(current)

    for name in sorted(by_name):
        if name in skipped or colour[name] != WHITE:
            continue
        _visit(name)

    return [by_name[n] for n in order if n not in skipped]


# ---------------------------------------------------------------------------
# Module import helper
# ---------------------------------------------------------------------------


def _import_module_from_file(
    plugin_name: str,
    file_path: Path,
) -> ModuleType | None:
    """Import a Python file as a synthetic module.

    Delegates the core importlib mechanics to :func:`import_module_from_path`.
    This wrapper builds the module name and handles error logging.

    Args:
        plugin_name: Plugin identifier, used to build the module name.
        file_path: Absolute path to the ``.py`` file.

    Returns:
        The imported module, or ``None`` if the import fails.

    """
    module_name = f"_plugin_{plugin_name}_{file_path.stem}"

    try:
        return import_module_from_path(module_name, file_path)
    except Exception:
        log.exception("failed to import %s for plugin '%s'", file_path, plugin_name)
        return None
