"""Parse @on() decorator subscriptions from plugin source files.

Walks Python AST to find functions decorated with @on("literal.string").
Rejects non-literal arguments (f-strings, variables, conditionals).
Writes results to events.toml per plugin; reads them back for the loader.
"""

from __future__ import annotations

import ast
import tomllib
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


@dataclass
class Subscription:
    """A single event subscription discovered from an @on() decorator."""

    event_name: str
    handler_name: str
    module: str  # e.g., "handlers" for handlers.py
    line: int


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def parse_plugin_subscriptions(plugin_dir: Path) -> list[Subscription]:
    """Parse all .py files in a plugin directory for @on() decorators."""
    subs: list[Subscription] = []
    for py_file in sorted(plugin_dir.glob("*.py")):
        subs.extend(_parse_file(py_file))
    return subs


def write_events_toml(plugin_dir: Path, subscriptions: list[Subscription]) -> Path:
    """Write subscriptions to events.toml in the plugin directory.

    If *subscriptions* is empty, removes any existing events.toml
    (no point keeping an empty file around).
    """
    toml_path = plugin_dir / "events.toml"

    if not subscriptions:
        toml_path.unlink(missing_ok=True)
        return toml_path

    lines = [
        "# Auto-generated by `v plugins rescan`. Do not edit manually.",
        "# Source: @on() decorators in plugin source files.",
        "",
    ]

    for sub in sorted(subscriptions, key=lambda s: (s.event_name, s.handler_name)):
        lines.append("[[subscriptions]]")
        lines.append(f'event = "{sub.event_name}"')
        lines.append(f'handler = "{sub.handler_name}"')
        lines.append(f'module = "{sub.module}"')
        lines.append(f"line = {sub.line}")
        lines.append("")

    toml_path.write_text("\n".join(lines) + "\n")
    return toml_path


def read_events_toml(plugin_dir: Path) -> list[Subscription]:
    """Read events.toml and return subscriptions.

    Returns an empty list if the file does not exist.
    """
    toml_path = plugin_dir / "events.toml"
    if not toml_path.exists():
        return []

    data = tomllib.loads(toml_path.read_text())

    return [
        Subscription(
            event_name=s["event"],
            handler_name=s["handler"],
            module=s["module"],
            line=s.get("line", 0),
        )
        for s in data.get("subscriptions", [])
    ]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _parse_file(path: Path) -> list[Subscription]:
    """Parse a single Python file for @on() subscriptions.

    Only considers module-level functions. @on() on nested functions
    or class methods is logged as a warning and skipped.
    """
    import logging as _logging

    _log = _logging.getLogger(__name__)

    source = path.read_text()
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    module = path.stem
    subs: list[Subscription] = []

    # Use identity (id) of module-level function nodes, not names, to
    # correctly handle shadowed names (e.g. top-level 'foo' and nested 'foo').
    top_level_func_ids: set[int] = set()
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            top_level_func_ids.add(id(node))

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        # Skip nested functions and class methods with a warning.
        if id(node) not in top_level_func_ids:
            if _has_on_decorator(node):
                _log.warning(
                    "%s:%d: @on() on nested function or method '%s' -- ignored "
                    "(only module-level functions are supported)",
                    path,
                    node.lineno,
                    node.name,
                )
            continue
        for decorator in node.decorator_list:
            sub = _extract_on_decorator(decorator, node.name, module, path)
            if sub:
                subs.append(sub)
    return subs


def _has_on_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Return True if the function has any @on(...) decorator."""
    for dec in node.decorator_list:
        if not isinstance(dec, ast.Call):
            continue
        func = dec.func
        if (isinstance(func, ast.Name) and func.id == "on") or (isinstance(func, ast.Attribute) and func.attr == "on"):
            return True
    return False


def _extract_on_decorator(
    decorator: ast.expr,
    fn_name: str,
    module: str,
    path: Path,
) -> Subscription | None:
    """Extract subscription from an @on("literal") decorator.

    Matches both ``@on("event")`` and ``@bus.on("event")`` call forms.
    Raises TypeError if the decorator is recognized as @on() but the
    argument is not a string literal (variables, f-strings, etc.).
    """
    if not isinstance(decorator, ast.Call):
        return None

    func = decorator.func
    # Match bare `on(...)` or attribute `<something>.on(...)`.
    is_on = (isinstance(func, ast.Name) and func.id == "on") or (isinstance(func, ast.Attribute) and func.attr == "on")
    if not is_on:
        return None

    if not decorator.args:
        import logging as _logging

        _logging.getLogger(__name__).warning(
            "%s:%d: bare @on() with no arguments -- ignored",
            path,
            decorator.lineno,
        )
        return None

    arg = decorator.args[0]
    if not isinstance(arg, ast.Constant) or not isinstance(arg.value, str):
        raise TypeError(
            f"{path}:{decorator.lineno}: @on() argument must be a string literal, "
            f"got {type(arg).__name__}. Non-literal arguments are not supported."
        )

    return Subscription(
        event_name=arg.value,
        handler_name=fn_name,
        module=module,
        line=decorator.lineno,
    )
